Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64" # Ubuntu 22.04 LTS

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl openssh-client
  SHELL

  config.vm.define "argomezS" do |server|
    server.vm.hostname = "argomezS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--name", "argomezS"]
        vb.memory = 3072
        vb.cpus = 2
    end
    server.vm.provision "shell", path: "scripts/argomezS.sh"
  end

end
